### ISSUE TITLE
[Bug]: Redirect after login sends me again to login page

### ISSUE THREAD

**Issue by aixxo** [Supernova3339/changerawr#7]
### 🐛 What happened?

After initial setup, when login in. I get redirected again to login.

I followed the installation process for Docker (non production)
`
# Clone the repository
git clone https://github.com/supernova3339/changerawr.git
cd changerawr

docker compose up --build

`

Also on the console is following message:
`
app-1       | ┌─────────────────────────────────────────────────────────┐
app-1       | │  Update available 6.6.0 -> 6.10.1                       │
app-1       | │  Run the following to update                            │
app-1       | │    npm i --save-dev prisma@latest                       │
app-1       | │    npm i @prisma/client@latest                          │
app-1       | └─────────────────────────────────────────────────────────┘
`
Maybe there are some commits missing in branch main?

### ✅ What should have happened?

Expected to see the Main Webinterface.

### 🔄 Steps to Reproduce

1. 
2. 
3. 
4.

### 📊 How often does this happen?

Every time (100%)

### 🌐 Browser

Safari

### 📱 Device Type

Desktop (macOS)

### 🎯 Which part of Changerawr?

Authentication / Login

### ⚡ Bug Severity

Critical - Completely blocks me from using Changerawr

### ❌ Error Messages

```text
No Error in the webbrowser
```

### 🔍 Console Output (For Developers)

```shell
postgres-1  | 2025-06-20 11:26:15.029 UTC [113] ERROR:  insert or update on table "AuditLog" violates foreign key constraint "AuditLog_userId_fkey"
postgres-1  | 2025-06-20 11:26:15.029 UTC [113] DETAIL:  Key (userId)=(login-attempt-1750418775024) is not present in table "User".
postgres-1  | 2025-06-20 11:26:15.029 UTC [113] STATEMENT:  INSERT INTO "public"."AuditLog" ("id","action","userId","targetUserId","details","createdAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING "public"."AuditLog"."id", "public"."AuditLog"."action", "public"."AuditLog"."userId", "public"."AuditLog"."targetUserId", "public"."AuditLog"."details", "public"."AuditLog"."createdAt"
app-1       | Failed to create login attempt audit log: Error [PrismaClientKnownRequestError]: 
app-1       | Invalid `prisma.auditLog.create()` invocation:
app-1       | 
app-1       | 
app-1       | Foreign key constraint violated: `AuditLog_userId_fkey (index)`
app-1       |     at async w (.next/server/app/api/auth/login/route.js:1:1844) {
app-1       |   code: 'P2003',
app-1       |   meta: [Object],
app-1       |   clientVersion: '6.6.0'
app-1       | }
app-1       | Generating tokens for user: cmc4q3z1y0000oa77z4idv5ba
app-1       | Access token generated successfully
app-1       | Refresh token created and stored in database
```

### 📋 Bug Report Checklist

- [x] I've searched existing issues and this isn't a duplicate
- [x] I can reproduce this bug consistently
- [x] I've included steps to reproduce the issue
- [x] I'd be willing to test a fix if provided

**Comment by Supernova3339** [comment]
I'll check this after work, thanks for letting me know. I have never tested on MacOS, are you deploying locally or to a server?

The compose file might be outdated as I haven't updated it since 0.2.9, can you try pulling the code directly ( without docker ) and attempt to run there and let me know if the same issue occurs?

**Comment by Supernova3339** [comment]
Looking into the issue now to see what's going wrong.

**Comment by Supernova3339** [comment]
I have not been able to reproduce this issue. Can you provide a video?

**Comment by Supernova3339** [comment]
Fixed the LOGIN_ATTEMPT audit log.

**Comment by DenbyDaily** [comment]
I have the same issue

**Comment by Supernova3339** [comment]
> I have the same issue

can you provide a video so I can reproduce this?

**Comment by palermostest25** [comment]
Still the same issue, I'm using Portainer and built the image. I also can't find the new available version.

**Comment by Supernova3339** [comment]
> OK, JUST FIXED IT. You need to define the next public app url at build time in the Dockerfile

This is not an issue, then. Thanks for letting me know!
